# Docker Compose file for Portainer
# Deploys Nginx Proxy Manager, ddclient, and Ghost with a dedicated MySQL database

version: '3.8' # Specifies the Docker Compose file format version

services:
  # Nginx Proxy Manager Service
  # Web interface for managing Nginx proxy hosts with SSL termination
  npm:
    image: 'jlesage/nginx-proxy-manager:latest' # Uses the latest official Nginx Proxy Manager image
    container_name: nginx-proxy-manager
    restart: unless-stopped # Restarts the container unless it's manually stopped
    ports:
      # These ports are exposed to the host machine
      - '8080:8080'   # Standard HTTP port
      - '4443:4443' # Standard HTTPS port
      - '8181:8181'   # Nginx Proxy Manager admin interface port
    volumes:
      # Persistent storage for Nginx Proxy Manager data, custom configurations, and SSL certificates
      - /portainer/npm/config:/config
    networks:
      - proxy-network # Connects to the custom proxy network
    depends_on:
      - ddclient # Ensures ddclient is started before npm attempts to proxy to it
      - ghost-server # Ensures ghost server is started before npm attempts to proxy to it

  # ddclient Service for Dynamic DNS
  # Automatically updates your Cloudflare DNS records with your dynamic public IP address
  ddclient:
    image: 'ddclient/ddclient:latest' # Uses a popular and reliable Dynamic DDNS image
    container_name: ddclient
    restart: unless-stopped # Restarts the container unless it's manually stopped
    environment:
      # Set your timezone to get accurate timestamps in logs
      - TZ=Etc/UTC # Example: America/New_York, Europe/London, Etc/UTC
    volumes:
      # Mounts the configuration file from the host into the container
      - /portainer/ddclient/ddclient.conf:/etc/ddclient/ddclient.conf:ro
    networks:
      - proxy-network # Connects to the custom proxy network

  # Ghost Blog Service
  # Professional publishing platform
  ghost-server:
    image: ghost:5 # Specifies Ghost version 5
    container_name: ghost-server
    cap_add:
      - CAP_SYS_NICE
    security_opt:
      - seccomp:unconfined
    restart: always
    ports:
      # Port 2368 is Ghost's default port.
      # Nginx Proxy Manager will connect to this port internally.
      # Exposing it to the host is optional if only accessing through NPM.
      - '2368:2368'
    depends_on:
      - ghost-db # Ensures the database is started before Ghost
    environment:
      # IMPORTANT: Update this URL to your actual public domain for Ghost
      url: https://yourdomain.com
      database__client: mysql
      database__connection__host: ghost-db # Connects to the ghost-db service name
      database__connection__user: root
      # IMPORTANT: Change this password and ensure it matches MYSQL_ROOT_PASSWORD in ghost-db
      database__connection__password: SuperSecurePassword
      database__connection__database: ghost-database
    volumes:
      # IMPORTANT: Ensure the host path '/portainer/ghost/content' exists on your Docker host
      - /portainer/ghost/content:/var/lib/ghost/content
    networks:
      - proxy-network

  # Ghost Database Service (MySQL)
  ghost-db:
    image: mysql:8 # Specifies MySQL version 8
    container_name: ghost-mysql-database
    security_opt:
      - seccomp:unconfined
    restart: always
    command: --mysql-native-password=ON # Enables native password authentication
    environment:
      # IMPORTANT: Change this password and ensure it matches database__connection__password in ghost-server
      MYSQL_ROOT_PASSWORD: SuperSecurePassword
      MYSQL_DATABASE: ghost-database # Optional: Creates the database on startup
    volumes:
      # IMPORTANT: Ensure the host path '/portainer/ghost/mysql' exists on your Docker host
      - /portainer/ghost/mysql:/var/lib/mysql
    networks:
      - proxy-network

# Define a custom Docker network
# This allows containers to communicate with each other by their service names
networks:
  proxy-network:
    driver: bridge # Uses the default bridge driver for the network